name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
      - "4.x"
      - "5.x"
      - "5.0"
    paths-ignore:
      - "*.md"
  pull_request:
    paths-ignore:
      - "*.md"

jobs:
  lint:
    name: Lint
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            architecture: x64
          - os: ubuntu-22.04-ppc64le
            architecture: ppc64le

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          architecture: ${{ matrix.architecture }}

      - name: Install dependencies
        run: npm install --ignore-scripts --only=dev

      - name: Run lint
        run: npm run lint

  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            architecture: x64
            node-version: 18
          - os: ubuntu-22.04
            architecture: x64
            node-version: 19
          - os: ubuntu-22.04
            architecture: x64
            node-version: 20
          - os: ubuntu-22.04
            architecture: x64
            node-version: 21
          - os: ubuntu-22.04
            architecture: x64
            node-version: 22
          - os: ubuntu-22.04
            architecture: x64
            node-version: 23
          - os: ubuntu-22.04-ppc64le
            architecture: ppc64le
            node-version: 18
          - os: ubuntu-22.04-ppc64le
            architecture: ppc64le
            node-version: 19
          - os: ubuntu-22.04-ppc64le
            architecture: ppc64le
            node-version: 20
          - os: ubuntu-22.04-ppc64le
            architecture: ppc64le
            node-version: 21
          - os: ubuntu-22.04-ppc64le
            architecture: ppc64le
            node-version: 22
          - os: ubuntu-22.04-ppc64le
            architecture: ppc64le
            node-version: 23
          - os: windows-latest
            architecture: x64
            node-version: 18
          - os: windows-latest
            architecture: x64
            node-version: 19
          - os: windows-latest
            architecture: x64
            node-version: 20
          - os: windows-latest
            architecture: x64
            node-version: 21
          - os: windows-latest
            architecture: x64
            node-version: 22
          - os: windows-latest
            architecture: x64
            node-version: 23

    name: Node.js ${{ matrix.node-version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: true

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          architecture: ${{ matrix.architecture }}

      - name: Configure npm loglevel
        run: |
          npm config set loglevel error
        shell: bash

      - name: Install dependencies
        run: npm install

      - name: Output Node and NPM versions
        run: |
          echo "Node.js version: $(node -v)"
          echo "NPM version: $(npm -v)"

      - name: Run tests
        shell: bash
        run: |
          npm run test-ci
          cp coverage/lcov.info "coverage/${{ matrix.node-version }}.lcov"

      - name: Collect code coverage
        run: |
          mv ./coverage "./${{ matrix.node-version }}"
          mkdir ./coverage
          mv "./${{ matrix.node-version }}" "./coverage/${{ matrix.node-version }}"

      - name: Upload code coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: ./coverage
          retention-days: 1

  coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install lcov
        shell: bash
        run: sudo apt-get -y install lcov

      - name: Collect coverage reports
        uses: actions/download-artifact@v3
        with:
          name: coverage
          path: ./coverage

      - name: Merge coverage reports
        shell: bash
        run: find ./coverage -name lcov.info -exec printf '-a %q\n' {} \; | xargs lcov -o ./coverage/lcov.info

      - name: Upload coverage report
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
